# Generated by Django 3.1.2 on 2021-03-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roll_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='web_mail',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
