# Generated by Django 3.1.2 on 2021-04-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210408_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='latexFile',
            field=models.FileField(blank=True, null=True, upload_to='latex'),
        ),
        migrations.AddField(
            model_name='resume',
            name='pdfFile',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='rFile',
            field=models.FileField(blank=True, null=True, upload_to='data'),
        ),
    ]