# Generated by Django 3.1.2 on 2021-05-27 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210502_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Techskills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pLanguages', models.CharField(max_length=100)),
                ('webTechs', models.CharField(max_length=100)),
                ('dbms', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('miscellaneous', models.CharField(max_length=100)),
                ('others', models.CharField(max_length=100)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proTitle', models.CharField(max_length=50)),
                ('proDate', models.CharField(max_length=20)),
                ('clubName', models.CharField(max_length=40)),
                ('githubLink', models.CharField(max_length=40)),
                ('proDes', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('roll', models.CharField(max_length=40, null=True)),
                ('stream', models.CharField(max_length=50, null=True)),
                ('programme', models.CharField(max_length=50, null=True)),
                ('minor', models.CharField(max_length=50, null=True)),
                ('webmail', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=50, null=True)),
                ('linkedIn', models.CharField(max_length=50, null=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Por',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('por', models.CharField(max_length=100)),
                ('porDesc', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.CharField(max_length=60, null=True)),
                ('expDes', models.TextField(null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtechBoard', models.CharField(max_length=50)),
                ('mtechGrade', models.CharField(max_length=10)),
                ('mtechYear', models.CharField(max_length=20)),
                ('btechBoard', models.CharField(max_length=50)),
                ('btechGrade', models.CharField(max_length=10)),
                ('btechYear', models.CharField(max_length=20)),
                ('ssBoard', models.CharField(max_length=50)),
                ('ssGrade', models.CharField(max_length=10)),
                ('ssYear', models.CharField(max_length=20)),
                ('sBoard', models.CharField(max_length=50)),
                ('sGrade', models.CharField(max_length=10)),
                ('sYear', models.CharField(max_length=20)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ach', models.CharField(max_length=60, null=True)),
                ('achDes', models.TextField(null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resume')),
            ],
        ),
    ]
