# Generated by Django 3.1.2 on 2021-05-27 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_achievement_course_education_experience_por_profile_projects_techskills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='rFile',
        ),
    ]
