# Generated by Django 3.1.2 on 2021-05-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_resume_rfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Techskill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=100)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resume')),
            ],
        ),
        migrations.DeleteModel(
            name='Techskills',
        ),
    ]
